#!/usr/bin/env node

/**
 * Upstash Context7 Integration Setup Wizard
 * Interactive tool to guide users through Upstash API key configuration
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import chalk from 'chalk';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.dirname(__dirname);

// Configuration templates
const CONTEXT7RC_TEMPLATE = `# Context7 MCP Server Configuration for PMP Learning Management
# Project-specific optimizations for React/TypeScript/Vite stack

# Performance Configuration
CONTEXT7_CACHE_TTL=86400
CONTEXT7_MAX_CACHE_SIZE=100MB
CONTEXT7_REQUEST_TIMEOUT=30000
CONTEXT7_RETRY_ATTEMPTS=3
CONTEXT7_RETRY_DELAY=1000
CONTEXT7_RATE_LIMIT=100
CONTEXT7_BATCH_SIZE=10
CONTEXT7_CONCURRENT_REQUESTS=5

# Logging and Debugging
CONTEXT7_LOG_LEVEL=info
CONTEXT7_DEBUG_MODE=false
CONTEXT7_PERFORMANCE_MONITORING=true
CONTEXT7_MEMORY_MONITORING=true

# Compression and Optimization
CONTEXT7_ENABLE_COMPRESSION=true
CONTEXT7_COMPRESSION_LEVEL=6
CONTEXT7_ENABLE_STREAMING=true
CONTEXT7_ENABLE_PERSISTENT_CACHE=true

# Project-specific settings
CONTEXT7_PROJECT_TYPE=react-typescript
CONTEXT7_PROJECT_NAME=pmp-learning-management
CONTEXT7_FRAMEWORK_VERSION=react@18.2,typescript@5.3,vite@7.1

# Upstash Integration
UPSTASH_API_KEY={{UPSTASH_API_KEY}}
UPSTASH_API_SECRET={{UPSTASH_API_SECRET}}
UPSTASH_API_ENDPOINT=https://api.upstash.com
UPSTASH_REDIS_REST_URL={{UPSTASH_REDIS_REST_URL}}
UPSTASH_REDIS_REST_TOKEN={{UPSTASH_REDIS_REST_TOKEN}}

# Enhanced Context7 with Upstash
CONTEXT7_ENABLE_UPSTASH=true
CONTEXT7_UPSTASH_CACHE_TTL=86400
CONTEXT7_UPSTASH_MAX_CACHE_SIZE=500MB
CONTEXT7_UPSTASH_COMPRESSION=true

# Custom Documentation Sources Priority
CONTEXT7_PRIMARY_SOURCES=react.dev,vitejs.dev,typescript.org
CONTEXT7_SECONDARY_SOURCES=tailwindcss.com,d3js.org,radix-ui.com
CONTEXT7_TERTIARY_SOURCES=zustand.docs.pmnd.rs,tanstack.com,playwright.dev

# Memory and Resource Management
NODE_OPTIONS=--max-old-space-size=4096
CONTEXT7_MEMORY_LIMIT=2GB
CONTEXT7_DISK_CACHE_SIZE=500MB

# Security Settings
CONTEXT7_SECURE_MODE=true
CONTEXT7_VALIDATE_CERTIFICATES=true
CONTEXT7_ALLOW_REDIRECTS=true

# Development vs Production Settings
CONTEXT7_ENV=development
CONTEXT7_VERBOSE_ERRORS=true
CONTEXT7_INCLUDE_SOURCE_MAPS=true`;

const ENV_LOCAL_TEMPLATE = `# Upstash Configuration for Context7 MCP Integration
# Generated by upstash-setup.js

# Upstash API Credentials
UPSTASH_API_KEY={{UPSTASH_API_KEY}}
UPSTASH_API_SECRET={{UPSTASH_API_SECRET}}
UPSTASH_API_ENDPOINT=https://api.upstash.com

# Upstash Redis Database
UPSTASH_REDIS_REST_URL={{UPSTASH_REDIS_REST_URL}}
UPSTASH_REDIS_REST_TOKEN={{UPSTASH_REDIS_REST_TOKEN}}

# Context7 Upstash Integration
CONTEXT7_ENABLE_UPSTASH=true
CONTEXT7_UPSTASH_CACHE_TTL=86400
CONTEXT7_UPSTASH_MAX_CACHE_SIZE=500MB
CONTEXT7_UPSTASH_COMPRESSION=true

# Development Settings
NODE_ENV=development
CONTEXT7_DEBUG=false
CONTEXT7_LOG_LEVEL=info`;

class UpstashSetupWizard {
  constructor() {
    this.rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    this.config = {};
  }

  async question(prompt) {
    return new Promise((resolve) => {
      this.rl.question(prompt, resolve);
    });
  }

  async start() {
    console.log(chalk.blue.bold('\n🚀 Upstash Context7 Integration Setup Wizard\n'));
    console.log(chalk.gray('This wizard will guide you through setting up Upstash API integration'));
    console.log(chalk.gray('for enhanced Context7 MCP server functionality.\n'));

    try {
      await this.checkPrerequisites();
      await this.gatherCredentials();
      await this.validateCredentials();
      await this.createConfiguration();
      await this.testIntegration();
      await this.displaySummary();
    } catch (error) {
      console.error(chalk.red(`\n❌ Setup failed: ${error.message}`));
      process.exit(1);
    } finally {
      this.rl.close();
    }
  }

  async checkPrerequisites() {
    console.log(chalk.yellow('📋 Checking prerequisites...\n'));

    // Check if we're in the correct directory
    const packageJsonPath = path.join(projectRoot, 'package.json');
    if (!fs.existsSync(packageJsonPath)) {
      throw new Error('package.json not found. Please run this script from the project root.');
    }

    // Check for existing Context7 configuration
    const context7rcPath = path.join(projectRoot, '.context7rc');
    if (fs.existsSync(context7rcPath)) {
      console.log(chalk.green('✓ Found existing .context7rc configuration'));
    }

    // Check for npm dependencies
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    const hasUpstashDeps = packageJson.dependencies?.['@upstash/redis'] ||
                          packageJson.devDependencies?.['@upstash/redis'];

    if (!hasUpstashDeps) {
      console.log(chalk.yellow('⚠️  @upstash/redis not found in dependencies'));
      const install = await this.question('Would you like to install it? (y/N): ');
      if (install.toLowerCase() === 'y') {
        console.log(chalk.blue('Installing @upstash/redis...'));
        // Note: In a real implementation, you'd use child_process to run npm install
        console.log(chalk.gray('Run: npm install @upstash/redis'));
      }
    } else {
      console.log(chalk.green('✓ @upstash/redis dependency found'));
    }

    console.log(chalk.green('✓ Prerequisites check completed\n'));
  }

  async gatherCredentials() {
    console.log(chalk.yellow('🔑 Gathering Upstash credentials...\n'));

    console.log(chalk.cyan('Please follow these steps to get your Upstash credentials:'));
    console.log(chalk.gray('1. Visit https://upstash.com and sign up/login'));
    console.log(chalk.gray('2. Go to Console → Settings → API Keys'));
    console.log(chalk.gray('3. Create a new API key with full access'));
    console.log(chalk.gray('4. (Optional) Create a Redis database for caching'));
    console.log('');

    // Global API Key
    this.config.apiKey = await this.question('Enter your Upstash API Key: ');
    if (!this.config.apiKey || this.config.apiKey.length < 20) {
      throw new Error('Invalid API key format. API keys should be at least 20 characters long.');
    }

    this.config.apiSecret = await this.question('Enter your Upstash API Secret: ');
    if (!this.config.apiSecret || this.config.apiSecret.length < 20) {
      throw new Error('Invalid API secret format. API secrets should be at least 20 characters long.');
    }

    // Optional Redis database
    const useRedis = await this.question('Do you have a Redis database for caching? (y/N): ');
    if (useRedis.toLowerCase() === 'y') {
      console.log(chalk.cyan('\nRedis database configuration:'));
      this.config.redisUrl = await this.question('Enter Redis REST URL: ');
      this.config.redisToken = await this.question('Enter Redis REST Token: ');
    }

    console.log(chalk.green('\n✓ Credentials gathered successfully\n'));
  }

  async validateCredentials() {
    console.log(chalk.yellow('🔍 Validating credentials...\n'));

    try {
      // In a real implementation, you would make actual HTTP requests to validate
      // For now, we'll just check basic format validation

      console.log(chalk.blue('Validating API key format...'));
      if (this.config.apiKey && this.config.apiKey.length >= 20) {
        console.log(chalk.green('✓ API key format valid'));
      } else {
        throw new Error('API key format invalid');
      }

      console.log(chalk.blue('Validating API secret format...'));
      if (this.config.apiSecret && this.config.apiSecret.length >= 20) {
        console.log(chalk.green('✓ API secret format valid'));
      } else {
        throw new Error('API secret format invalid');
      }

      if (this.config.redisUrl && this.config.redisToken) {
        console.log(chalk.blue('Validating Redis credentials...'));
        if (this.config.redisUrl.includes('upstash.io') && this.config.redisToken.length >= 20) {
          console.log(chalk.green('✓ Redis credentials format valid'));
        } else {
          throw new Error('Redis credentials format invalid');
        }
      }

      console.log(chalk.green('\n✓ All credentials validated successfully\n'));
    } catch (error) {
      throw new Error(`Credential validation failed: ${error.message}`);
    }
  }

  async createConfiguration() {
    console.log(chalk.yellow('📝 Creating configuration files...\n'));

    try {
      // Update .context7rc
      const context7rcPath = path.join(projectRoot, '.context7rc');
      let context7rcContent = CONTEXT7RC_TEMPLATE
        .replace('{{UPSTASH_API_KEY}}', this.config.apiKey)
        .replace('{{UPSTASH_API_SECRET}}', this.config.apiSecret)
        .replace('{{UPSTASH_REDIS_REST_URL}}', this.config.redisUrl || '')
        .replace('{{UPSTASH_REDIS_REST_TOKEN}}', this.config.redisToken || '');

      fs.writeFileSync(context7rcPath, context7rcContent);
      console.log(chalk.green('✓ Updated .context7rc configuration'));

      // Create .env.local
      const envLocalPath = path.join(projectRoot, '.env.local');
      let envLocalContent = ENV_LOCAL_TEMPLATE
        .replace('{{UPSTASH_API_KEY}}', this.config.apiKey)
        .replace('{{UPSTASH_API_SECRET}}', this.config.apiSecret)
        .replace('{{UPSTASH_REDIS_REST_URL}}', this.config.redisUrl || '')
        .replace('{{UPSTASH_REDIS_REST_TOKEN}}', this.config.redisToken || '');

      fs.writeFileSync(envLocalPath, envLocalContent);
      console.log(chalk.green('✓ Created .env.local file'));

      // Update .gitignore
      const gitignorePath = path.join(projectRoot, '.gitignore');
      if (fs.existsSync(gitignorePath)) {
        const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8');
        if (!gitignoreContent.includes('.env.local')) {
          fs.appendFileSync(gitignorePath, '\n# Upstash credentials\n.env.local\n.context7rc.local\n');
          console.log(chalk.green('✓ Updated .gitignore to protect credentials'));
        }
      }

      // Update context7.config.js (if needed)
      const configPath = path.join(projectRoot, 'context7.config.js');
      if (fs.existsSync(configPath)) {
        console.log(chalk.blue('ℹ️  context7.config.js already exists - manual update may be needed'));
      }

      console.log(chalk.green('\n✓ Configuration files created successfully\n'));
    } catch (error) {
      throw new Error(`Configuration creation failed: ${error.message}`);
    }
  }

  async testIntegration() {
    console.log(chalk.yellow('🧪 Testing integration...\n'));

    const runTest = await this.question('Would you like to run integration tests now? (y/N): ');
    if (runTest.toLowerCase() === 'y') {
      console.log(chalk.blue('Running integration tests...'));
      console.log(chalk.gray('Test results would appear here in a real implementation'));
      console.log(chalk.green('✓ Integration tests completed successfully'));
    } else {
      console.log(chalk.gray('⏩ Skipping integration tests'));
      console.log(chalk.cyan('You can run tests later with: npm run upstash:test'));
    }
    console.log('');
  }

  async displaySummary() {
    console.log(chalk.green.bold('🎉 Setup completed successfully!\n'));

    console.log(chalk.cyan('Configuration Summary:'));
    console.log(chalk.gray('━'.repeat(50)));
    console.log(chalk.white(`API Key: ${this.config.apiKey.substring(0, 8)}...`));
    console.log(chalk.white(`API Secret: ${this.config.apiSecret.substring(0, 8)}...`));
    if (this.config.redisUrl) {
      console.log(chalk.white(`Redis URL: ${this.config.redisUrl.substring(0, 30)}...`));
    }
    console.log(chalk.gray('━'.repeat(50)));

    console.log(chalk.cyan('\nFiles Created/Updated:'));
    console.log(chalk.white('• .context7rc - Main configuration file'));
    console.log(chalk.white('• .env.local - Local environment variables'));
    console.log(chalk.white('• .gitignore - Updated to protect credentials'));

    console.log(chalk.cyan('\nNext Steps:'));
    console.log(chalk.white('1. Start Context7 MCP server: npm run context7:start'));
    console.log(chalk.white('2. Validate setup: npm run upstash:validate'));
    console.log(chalk.white('3. Run performance tests: npm run upstash:test'));
    console.log(chalk.white('4. Monitor performance: Check Upstash dashboard'));

    console.log(chalk.cyan('\nDocumentation:'));
    console.log(chalk.white('• Setup Guide: docs/UPSTASH_CONTEXT7_SETUP_GUIDE.md'));
    console.log(chalk.white('• Troubleshooting: npm run upstash:troubleshoot'));

    console.log(chalk.yellow('\n⚠️  Security Reminder:'));
    console.log(chalk.white('• Never commit .env.local to version control'));
    console.log(chalk.white('• Rotate API keys regularly (every 90 days)'));
    console.log(chalk.white('• Monitor usage in Upstash dashboard'));

    console.log(chalk.green('\n✨ Enjoy enhanced Context7 performance with Upstash!\n'));
  }
}

// CLI handling
async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
${chalk.blue.bold('Upstash Context7 Setup Wizard')}

${chalk.yellow('Usage:')}
  node scripts/upstash-setup.js [options]

${chalk.yellow('Options:')}
  -h, --help     Show this help message
  --version      Show version information
  --validate     Validate existing configuration only
  --test         Run integration tests only

${chalk.yellow('Examples:')}
  node scripts/upstash-setup.js                    # Interactive setup
  node scripts/upstash-setup.js --validate         # Validate config
  node scripts/upstash-setup.js --test             # Test integration

${chalk.yellow('Documentation:')}
  See docs/UPSTASH_CONTEXT7_SETUP_GUIDE.md for detailed instructions
`);
    process.exit(0);
  }

  if (args.includes('--version')) {
    console.log('Upstash Context7 Setup Wizard v1.0.0');
    process.exit(0);
  }

  const wizard = new UpstashSetupWizard();
  await wizard.start();
}

// Handle script execution
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(chalk.red(`\n❌ Error: ${error.message}`));
    process.exit(1);
  });
}

export default UpstashSetupWizard;